### ISSUE TITLE
Refresh cache token when machine hibernate

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/learn.forge.viewmodels#13]
Although elegant, the `setTimeout` fails if the machine hibernate (which happens on localhost), after that the access_token does not refresh and we need to restart the project. 

https://github.com/Autodesk-Forge/learn.forge.viewmodels/blob/nodejs/routes/common/oauth.js#L42

**Comment by petrbroz** [comment]
Fixed with pull request #52.
