### ISSUE TITLE
Repeatedly adding a change event handler during file upload

### ISSUE THREAD

**Issue by petrbroz** [Autodesk-Forge/learn.forge.viewmodels#14]
The client side code for file uploading (https://github.com/Autodesk-Forge/learn.forge.viewmodels/blob/nodejs/public/js/ForgeTree.js#L143) is adding a new `change` event handler every time the user uses the "Upload File" action. So, for example, when the user is uploading a 5th file without reloading the page, the `change` event handler (and a post request to the server) is actually triggered 5 times.

**Comment by augustogoncalves** [comment]
Oh, I see, let's fix that :-)

**Comment by petrbroz** [comment]
Awesome! 👍
