### ISSUE TITLE
Error in Gettoken

### ISSUE THREAD

**Issue by sherbert18** [Autodesk-Forge/learn.forge.viewmodels#15]
I can log in using the 3 legged authentication but once I accept the permissions then I get this error. 

Error calling Gettoken: The underlying connection was closed: An unexpected error occurred on a send.

**Comment by augustogoncalves** [comment]
this is probably happening due TLS migration, please check if you have .NET 4.6 or newer

https://forge.autodesk.com/blog/tls-12-net-developers

**Comment by sherbert18** [comment]
Here is the function that I am getting the error in. Is this 3-legged Authentication?  

 [HttpGet]
    [Route("api/forge/oauth/url")]
    public string GetOAuthURL()
    {
      // prepare the sign in URL
      Scope[] scopes = { Scope.DataRead };
      ThreeLeggedApi _threeLeggedApi = new ThreeLeggedApi();
      string oauthUrl = _threeLeggedApi.Authorize(
        Credentials.GetAppSetting("FORGE_CLIENT_ID"),
        oAuthConstants.CODE,
        Credentials.GetAppSetting("FORGE_CALLBACK_URL"),
        new Scope[] { Scope.DataRead, Scope.ViewablesRead });

      return oauthUrl;
    }

**Comment by augustogoncalves** [comment]
I just downloaded the source for 3-legged (which is NOT this repo) and compiled with VS2017, works fine. Please make sure to **Rebuild** the project.

https://github.com/Autodesk-Forge/learn.forge.viewhubmodels/archive/net.zip

**Comment by rytmis** [comment]
There's a fair chance, that this error happens, because the API server no longer responds to obsolete TLS versions, and your app is running with defaults that try an older version of TLS.

Try adding this somewhere around the startup code of your app:

>             ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by edipof** [comment]
> There's a fair chance, that this error happens, because the API server no longer responds to obsolete TLS versions, and your app is running with defaults that try an older version of TLS.
> 
> Try adding this somewhere around the startup code of your app:
> 
> > ```
> >         ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
> > ```

This worked for me. Thanks :)
