### ISSUE TITLE
3D model not loading on the viewer

### ISSUE THREAD

**Issue by nitoniso** [Autodesk-Forge/learn.forge.viewmodels#16]
I used visual studio 2015 and I am receiving the error: 

`Failed to load resource: the server responded with a status of 404 (Not Found)
ForgeViewer.js:20 Uncaught TypeError: Cannot read property 'search' of null
    at onDocumentLoadSuccess (ForgeViewer.js:20)
    at b.ViewingApplication.<anonymous> (viewer3D.js:151999)
    at f (viewer3D.js:139004)
    at XMLHttpRequest.m (viewer3D.js:74916)`
on the web console. How do I resole the error so that I can see my 3d model on the viewe

**Comment by nitoniso** [comment]
I pressed the translation button but it is showing a stream of continuous errors in the console.
![forgeexample](https://user-images.githubusercontent.com/41240441/50330355-9129fe80-0503-11e9-9291-f54e3484f581.JPG). Please see the picture uploaded and that number I circled in red is keeping on increasing

**Comment by augustogoncalves** [comment]
this may happen after you load and reload models and resize the window. You can simply refresh it or adjust the `ForgeViewer.js` like [this other sample](https://github.com/Autodesk-Forge/model.derivative-WebAPI-sample/blob/master/forgeSample/wwwroot/js/ForgeViewer.js#L22), lines 22 to 30.

**Comment by nitoniso** [comment]
Thank you. It worked the problem I have now is the 3d models that I
uploaded disappears everyday i have to upload it again

**Comment by dukedhx** [comment]
You need to specify retention policy to keep the objects longer than 24 hours when you create the bucket: 
- https://forge.autodesk.com/en/docs/data/v2/developers_guide/retention-policy/
- https://forge.autodesk.com/en/docs/data/v2/reference/http/buckets-POST/
