### ISSUE TITLE
.env.example file missing

### ISSUE THREAD

**Issue by ishashankbhagat** [Autodesk-Forge/learn.forge.viewmodels#18]
I cannot find the .env.example file

**Comment by augustogoncalves** [comment]
it depends on the programming language and IDE, for Nodejs you'll the required env vars at the readme: https://github.com/Autodesk-Forge/learn.forge.viewmodels/tree/nodejs

**Comment by petrbroz** [comment]
I agree. While the _.env_ file is typical for vscode, this sample app doesn't really use that many env. variables to justify the need for such an example file. If you're using vscode, simply add the `FORGE_CLIENT_ID` and `FORGE_CLIENT_SECRET` to your launch.json directly.
