### ISSUE TITLE
Only 10 objects listed per bucket

### ISSUE THREAD

**Issue by petrbroz** [Autodesk-Forge/learn.forge.viewmodels#29]
I've noticed this in the [nodejs](https://github.com/Autodesk-Forge/learn.forge.viewmodels/tree/nodejs) branch, but other branches/languages are probably affected, too. When getting objects of a specific bucket, the [forge-apis](https://www.npmjs.com/package/forge-apis) only return 10 items by default. The code should either set a higher limit, or better, collect the objects in a loop.

**Comment by augustogoncalves** [comment]
good point @petrbroz, maybe as short & easy for the tutorial, adjust get buckets & get objects to 100 (max allowed value)?

**Comment by petrbroz** [comment]
Sounds good. Setting the page size to 100 and adding a code comment explaining the situation should suffice imho. Let me put together a PR.
