### ISSUE TITLE
Error while creating a new bucket

### ISSUE THREAD

**Issue by szyilmaz** [Autodesk-Forge/learn.forge.viewmodels#35]
while creating a new bucket like "zaferbucket" i'm getting an internal server error (500)

**ExceptionMessage: "Error calling CreateBucket: {\"reason\":\"Valid field 'bucketKey' must be of the form  [-_.a-z0-9]{3,128}\"}"**

![error](https://user-images.githubusercontent.com/46131381/79719683-c1480400-82e7-11ea-942b-cdbda07be2f4.JPG)

**Comment by augustogoncalves** [comment]
please ensure that your bucketKey does not contain any spaces, sometimes when you copy/paste the clientId it comes with a space in the end :) 

in future, please post questions via [StackOverflow](https://stackoverflow.com/tags/autodesk-forge)
