### ISSUE TITLE
ASP.NET Core sample - HTTPS issues

### ISSUE THREAD

**Issue by petrbroz** [Autodesk-Forge/learn.forge.viewmodels#42]
If it's not necessary, I'd suggest to remove the HTTPS redirection from the ASP.NET Core sample:

https://github.com/Autodesk-Forge/learn.forge.viewmodels/blob/netcore/Startup.cs#L28

It can cause issues with certificates. For example, on my macOS the server app would always redirect me from localhost:5000 (HTTP) to localhost:5001 (HTTPS) but the certificate wasn't working and had to be worked around: https://www.c-sharpcorner.com/article/how-to-enforce-htts-development-certificate-for-asp-net-core/.

And after resolving the certificate problem, there are CORS issues as well:

```
Access to XMLHttpRequest at 'https://localhost:5001/api/forge/oss/buckets?id=%23' (redirected from 'http://localhost:5000/api/forge/oss/buckets?id=%23') from origin 'http://localhost:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by augustogoncalves** [comment]
should be fine to remove, I believe this is the default template for this file.
