### ISSUE TITLE
git clone instruction in README

### ISSUE THREAD

**Issue by jeanflower** [Autodesk-Forge/learn.forge.viewmodels#45]
The instructions in README say
git clone https://github.com/autodesk-forge/forge.learning.viewmodels
perhaps they should say
git clone https://github.com/Autodesk-Forge/learn.forge.viewmodels.git
?

**Comment by petrbroz** [comment]
Good point, will fix that. Thank you!

**Comment by petrbroz** [comment]
I've submitted a couple of PRs changing the readme files for different languages, and the git url is fixed there.
