### ISSUE TITLE
Need instructions to connect to BIM360 Hub (integration tab)

### ISSUE THREAD

**Issue by wallabyway** [Autodesk-Forge/learn.forge.viewmodels#6]
Couldn't see my BIM360 files/folders because there were no instructions on how to add Forge Client ID into the BIM360 Admin page... 

like this one...
https://bim360xls.autodesk.io/# -> click Config button -> step by step instructions

Thank you

**Comment by augustogoncalves** [comment]
this sample code is for 2-legged only, so not applicable... on the viewhubmodels there is a warning before sign-in, [see here](https://github.com/Autodesk-Forge/learn.forge.viewhubmodels/blob/master/index.html#L54).
